### PR TITLE
Fix compatibility with Contao 4.9 preview_switch

### LINKED ISSUE #42: XMLHttpRequest for contao/preview_switch of unpublished items
In Contao 4.9 the link to the `contao/preview_switch` of unpublished items is not working anymore - generated here:
https://github.com/madeyourday/contao-rocksolid-frontend-helper/blob/519ed500a582069baaa1bb9456039f706f7b7ab0/src/FrontendHooks.php#L286

The route call should be refactored to XMLHttpRequest - I guess somewhere here:
https://github.com/madeyourday/contao-rocksolid-frontend-helper/blob/519ed500a582069baaa1bb9456039f706f7b7ab0/src/Resources/public/js/main.js#L433

### PR DESCRIPTION
**Pull request by rabauss**
Fix #42 

I'm not sure if this is required from Contao 4.9 or earlier!

### CODE REVIEW

**Comment by ausi** [comment]
I changed the implementation a little bit. Can you please confirm if this works for you too?

File: src/Resources/public/js/main.js [hunk 1]
```diff
@@ -170,7 +170,7 @@ document.addEventListener('DOMContentLoaded', function() {
 		}
 		return data.labels[key];
 	};
-	var switchBackend = function(url, requestType, data, callback) {
+	var postToIframe = function(url, data, isXmlHttpRequest, callback) {
```
Comment (rabauss) [inline src/Resources/public/js/main.js:173]: If you do not want to rename that method to prevent BC break, the new parameter should be added last, shouldn't it?

**Comment by rabauss** [comment]
Yes, it still works for me! And your JS part looks better 👍

File: src/Resources/public/js/main.js (hunk 1 above)
Comment (ausi) [reply src/Resources/public/js/main.js]: Renamed in abd7a6a97858ee9980ba9a19790089e10b711673.

The method is private so there should be no BC break I think.

**Comment by ausi** [comment]
Thank you @rabauss
